spring:
    application:
        name: master
    datasource:
        url: jdbc:postgresql://localhost:5432/air_conditioner_system
        username: root
        password: root
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
            ddl-auto: none
        open-in-view: false
        show-sql: true
    # 启用 Bean 懒加载, 加速启动速度
    main:
        lazy-initialization: true
    # 启动虚拟线程的支持
    threads:
        virtual:
            enabled: true
springdoc:
    api-docs:
        path: /api-docs
        enabled: true
    swagger-ui:
        # 可以通过这个 url 启动 swagger-ui 方便调试
        path: /swagger-ui.html
        enabled: true

master:
    fixedRate: 1000
    pollingInterval: 500
    EXPIRY_DURATION: 100

slave:
    defaultTemp: 2200